### PR TITLE
Press Enter to select the first version found

### PR DESCRIPTION
**Pull request by tomsquest**
Allow to simply press Enter to select the first version found.

### CODE REVIEW

**Comment by pogman-code** [comment]
That's a good idea but I'd like to keep the "Nothing to do" fallback in case I don't want to download a subtitle (if it does not match my release for instance).

What we can do for that is to surround the `input` call with a `try/except KeyboardInterrupt` so pressing Ctrl+C will print "Nothing to do!" and continue to the next video file.

```python
version = "0"
try:
    version = input('Download number? [0]')
except (KeyboardInterrupt):
    print(colored("\nNothing to do!", "yellow"),
          end="\n\n")
    continue
```

Are you OK with this solution?

**Comment by tomsquest** [comment]
It's indeed better and enable to skip an episode (when retrying for example).

I pushed a new commit with your suggestion.

BTW, I did not set `version = 0` at the top, as I had a warning in my IDE, so I set the default after the `input(...)`.

**Comment by pogman-code** [comment]
Merged with master manually (squash + FF merge)

**Comment by pogman-code** [comment]
FYI: Available in 1.1.15
https://pypi.python.org/pypi/addic7ed/1.1.5

**Pull request closed without merging**
